### ISSUE TITLE
How to use this with Angular 13

### ISSUE THREAD

**Issue by aaron170** [cloudnc/ngx-favicon#51]
Hello

I am using Angular 13 build and trying to get this working but getting error that it works only in Angular 14 so I need to upgrade my project to Angular 14.
![image](https://github.com/cloudnc/ngx-favicon/assets/19680243/c5e8aa62-b1b4-4214-b02e-5b9b77221925)

Is there any solution to this?
As I cannot upgrade to 14 as there are many dependencies that will need to change.
I have different environments for different clients so I think this is the best way I can apply Favicons for each client.
Please help me run this on Angular 13 build. Thanks

**Comment by maxime1992** [comment]
Looking at the [releases](https://github.com/cloudnc/ngx-favicon/releases) it looks like you can just use anything before `4.1.0`. 

![image](https://github.com/cloudnc/ngx-favicon/assets/4950209/da795d7d-6305-424d-8ee7-378d0c2aaa31)

So I'd advise you to use `4.0.1`.

**Comment by aaron170** [comment]
Thanks @maxime1992 
I figured out that later. I was searching for releases and found out about the different version. And Version 4.0.0 worked for me.

Thanks for pointing it out. Cheers!
